name: PR Preview

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]

jobs:
  pr-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Deploy PR preview
      - name: Deploy Preview
        if: github.event.action != 'closed'
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./ # root of your repo (adjust if files are in /site etc.)
          preview-branch: gh-pages
          preview-repo: cost-splits/previews

      # Remove preview when PR closes
      - name: Remove Preview
        if: github.event.action == 'closed'
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./
          preview-branch: gh-pages
          preview-repo: cost-splits/previews
