name: PR Preview

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]

jobs:
  deploy-preview:
    environment: pr-preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Deploy preview when PR is open or updated
      - name: Deploy PR Preview
        uses: rossjrw/pr-preview-action@v1
        if: >
          ( ( contains(join(github.event.pull_request.labels.*.name, ','),
          'preview') &&
              (github.event.action == 'opened' || github.event.action ==
          'reopened' || github.event.action == 'synchronize')
            )
            ||
            (github.event.action == 'labeled' && github.event.label.name ==
          'preview') )
        with:
          source-dir: ./ # root of your repo (adjust if your HTML lives in a subfolder)
          deploy-repository: "cost-splits/previews"
          token: ${{ secrets.PR_PREVIEW_PAT }}
          action: deploy

      # Remove preview when PR is closed
      - name: Remove PR Preview
        uses: rossjrw/pr-preview-action@v1
        if: >
          ( (github.event.action == 'unlabeled' && github.event.label.name ==
          'preview')
            ||
            (github.event.action == 'closed' &&
              contains(join(github.event.pull_request.labels.*.name, ','),
          'preview')) )
        with:
          source-dir: ./
          deploy-repository: "cost-splits/previews"
          token: ${{ secrets.PR_PREVIEW_PAT }}
          action: remove
